# Site setings
name: 'Artik blue'
title: 'Artik blue's digital thoughts'
description: 'Alternate use of modern technology also known as hacking.'
meta_description: 'Alternate use of modern technology also known as hacking.'
#logo: 'assets/images/logo.png'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /
production_url: https://artik.blue/
disqus: 'artikblue'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: ''


# Author
author:
    name: Artikblue
    image: avatar.png
    display_name: Artikblue
    gravatar: 76ead780a562cf43aaa438f46ad3fb93
    email: artikblue@protonmail.com
    web: artik.blue
    twitter: https://twitter.com/artikblue
    description: "Alternate use of modern technology also known as hacking."
# Contact form setings
email: artikblue@protonmail.com
contact_page_description: "The alternate use of modern technologies, aka hacking."
thankyou_page_description: "Thank you"

# Social links
twitter: 'artikblue'
#facebook: 'username'
github: 'artikblue'
#codepen: 'username'
#dribbble: 'username'
medium: '@artikblue'
#instagram: 'username'
#pinterest: 'username'
#linkedin: 'krishnallamilli'
#producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Reversing
    url: /reversing
#  - text: Contact Me
#    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown
#highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
